### ISSUE TITLE
[request] about config

### ISSUE THREAD

**Issue by whikk** [hamadmarri/TT-CPU-Scheduler#2]
Hi, I don't know how to configure the config, using TT. I want two copies of the config, one for the game/performance and one for the responsive/latency. Thank you!

**Comment by whikk** [comment]
or a suggestion like this.
![image](https://user-images.githubusercontent.com/75515273/140442494-cb1664e1-9815-4d67-8ce2-9ce00439e79d.png)

**Comment by hamadmarri** [comment]
Hello @whikk 

For latency and response I recommend using the `-rt` patch and:
```
CONFIG_HAVE_PREEMPT_LAZY=y
CONFIG_PREEMPT_LAZY=y
CONFIG_PREEMPT_RT=y
CONFIG_PREEMPT_COUNT=y
CONFIG_PREEMPTION=y
CONFIG_PREEMPT_RCU=y
CONFIG_HAVE_PREEMPT_DYNAMIC=y
CONFIG_PREEMPT_NOTIFIERS=y
CONFIG_DRM_I915_PREEMPT_TIMEOUT=640

CONFIG_NO_HZ_COMMON=y
CONFIG_NO_HZ_FULL=y
CONFIG_NO_HZ=y
CONFIG_HZ_1666=y
CONFIG_HZ=1666
```

For gaming or performance use the non `-rt` patch with:
```
CONFIG_NO_HZ_IDLE=y
CONFIG_HZ=833 or 500 from XanMod
CONFIG_PREEMPT_VOLUNTARY=y
```

You can also use these vm sysctl tunnings:
```
$ cat /etc/sysctl.d/10-vm.conf

vm.vfs_cache_pressure = 50
vm.dirty_background_ratio = 25
vm.dirty_ratio = 35
vm.swappiness = 10
```

**Comment by hamadmarri** [comment]
> or a suggestion like this. ![image](https://user-images.githubusercontent.com/75515273/140442494-cb1664e1-9815-4d67-8ce2-9ce00439e79d.png)

Those will be auto selected in both Baby and TT. No worries about them.

**Comment by whikk** [comment]
@hamadmarri Thank you so much for your advice!

**Comment by whikk** [comment]
And how to configure config for latency and response use the non `-rt` patch? I don't want to use rt kernel for now.

**Comment by hamadmarri** [comment]
> And how to configure config for latency and response use the non `-rt` patch? I don't want to use rt kernel for now.

Almost the same config except 
use CONFIG_PREEMPT instead of CONFIG_PREEMPT_RT

**Comment by whikk** [comment]
Ok
