### ISSUE TITLE
how to enable TT?

### ISSUE THREAD

**Issue by dxcvvxd** [hamadmarri/TT-CPU-Scheduler#21]
i `yay -S`'ed linux-tt package, it compiled and installed
what should i do next? thanks in regards

**Comment by ptr1337** [comment]
Boot into the kernel

**Comment by dxcvvxd** [comment]
@ptr1337 does that mean just rebooting? im not very good with linux terminology

**Comment by ptr1337** [comment]
Hi. 

Normally it should show the kernel in your bootloader. Depending on which bootloader you have, you need to generate a entry for it. 

Please check the arch wiki for this (grub or systemd boot)
